# Generated by Django 4.0.6 on 2022-09-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateAccount',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password1', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=10)),
            ],
        ),
    ]
